version: '3.9'

services:
  wordpress:
    env_file:
      - .env
    platform: linux/amd64
    depends_on: 
      - db
    build:
      context: .
      dockerfile: dockerfile.wp
    container_name: wp
    ports:
      - "8000:80"
    volumes:
      - ./themes/my-theme:/var/www/html/wp-content/themes/my-theme
      - ./media:/var/www/html/wp-content/uploads/custom-media
      - ./wp-init.sh:/usr/local/bin/wp-init.sh
      - ./wp-config-create.sh:/usr/local/bin/wp-config-create.sh
      - ./wait-for-db.sh://usr/local/bin/wait-for-db.sh
    command: ["bash", "/usr/local/bin/wp-init.sh"]
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      # auto-install settings:
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WP_URL: ${WP_URL}

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: wp-db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data: